command_timeout = 5000
# Replace the "â¯" symbol in the prompt with "âœ"
#[character]      # The name of the module we are configuring is "character"
#symbol = "âœ"     # The "symbol" segment is being set to "âœ"
#error_symbol = "âœ—"
#use_symbol_for_status = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

#[battery]
#full_symbol = "ğŸ”‹"
#charging_symbol = "âš¡ï¸"
#discharging_symbol = "ğŸ’€"

#[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
#threshold = 10
#style = "bold red"

#[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
#threshold = 30
#style = "bold yellow"

[directory]
truncation_length = 3

# docker
#[docker_context]
#symbol = "ğŸ‹ "
#disabled = false

# env variable
#[env_var]
#variable = "SHELL"
#default = "unknown shell"

# git

#[git_commit]
#commit_hash_length = 4

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "[++](green)"
#staged_count.enabled = true
#staged_count.style = "green"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

# hostname
#[hostname]
#ssh_only = false
#prefix = "âŸª"
#suffix = "âŸ«"
#trim_at = ".companyname.com"
#disabled = true

# kubernetes
[kubernetes]
format = '[â›µ ($context)|($namespace)](dimmed green) in '
#symbol = "â›µ "
#style = "dimmed green"
disabled = false
[kubernetes.context_aliases]
"homelab.harris.place" = "homelab"

#[memory_usage]
#disabled = false
#show_percentage = true
#show_swap = true
#threshold = -1
#symbol = " "
#separator = "/"
#style = "bold dimmed green"

[python]
pyenv_version_name = true
